### ISSUE TITLE
equals = equals ???????

### ISSUE THREAD

**Issue by C-Ryan0510** [TKU-IIT/FCC-Java-Course#7]
CorporateName n1 = new CorporateName("IBM"); 
CorporateName n2 = new CorporateName(new String("IBM"));
--
System.out.println(n1.equals(n2)); --->>>false

**Comment by min20120907** [comment]
Because your equals method is wrong. Maybe the way to compare strings are not String.equals?

**Comment by C-Ryan0510** [comment]
```java
///
public boolean equals(Object obj){
if(obj == this){
return true;
}
if(obj == null){
return false;
}
if(obj == obj){
return true;
}
if(obj == n1){
return true;
}

return false;
}
///
```

**Comment by min20120907** [comment]
that's wrong

**Comment by min20120907** [comment]
u need to make sure, the situation that the contents are the same, then equals can return a true value.

**Comment by min20120907** [comment]
@Onion0000 your issue is duplicated here.

**Comment by min20120907** [comment]
@C-Ryan0510 @Onion0000  Please check the equals method can be passed on these tests.

```java
Team a;
Team b = new Team("test");
Team c = new Team(new String("test"));
Team d = new Team();
Team e = new Team(null);
System.out.println(a.equals(d));   //True
System.out.println(b.equals(c));    //True
System.out.println(e.equals(d));   //True
```

**Comment by min20120907** [comment]
請仔細看看github issue上我寫的測試條件
那就是傳說中的hidden test
你要去實作equals method必須要實作integrity(不是FCC初始化的integrity), 除了比較object的位置以外，還要比較裡面的private members
請參考java.utils.Object.hashCode
還有java.utils.Object.equals

**Comment by C-Ryan0510** [comment]
@Override
    public boolean equals(Object obj){
        CorporateName n1 = (CorporateName)obj;
        if(obj==this||n1==this){
            return true;
        }else if(obj==obj){
            return true;
        }else if(obj==null){
            return false;
        }
        return (n1.name==this.name);
	}
    public boolean equals(CorporateName n1){
        int var = this.name.compareTo(n1.name);
	    if(n1==this){
		    return true;
	    }else if(var==0){
	        return true;
	    }
	    return false;
    }

**Comment by C-Ryan0510** [comment]
done
